version: '3.7'

services:     
  mariadb:
    container_name: mariadb-for-web-app
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: webdb
      MARIADB_USER: webdb
      MARIADB_PASSWORD: password
    ports:
      - "0.0.0.0:5023:3306"

  web:
    container_name: docker-web-app
    hostname: api
    build: ./
    ports:
      - "0.0.0.0:5003:5003"